### ISSUE TITLE
Green footer on "About" page floats depending on screen size

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#73] opened 2016-05-09 16:01 UTC
![image](https://cloud.githubusercontent.com/assets/4636824/15119185/8f2bce6e-15c4-11e6-8148-e25eb54af550.png)

Not a big deal if it doesn't get fixed, but wanted to point it out.

**Comment by mthong** [comment] 2016-05-09 16:02
As a bonus for reading this issue, you get a photo of my daughter from the background of my second monitor!

**Comment by LaurieSReynolds** [comment] 2016-05-09 16:59
I think this is a duplicate of #39 which was marked as low priority.

Adorable photo!

**Comment by mthong** [comment] 2016-05-09 17:32
Yeah, @dshapira and I decided #39 was low priority because we were only focused on the dashboard page which seems to have enough content to push the footer to the bottom of the screen even if it's quite a wide screen. But the About page doesn't have enough content so it is more likely that the footer will float even in with a relatively common screen size. Even then I don't think it's a major problem but it is going to be noticeable. 

Related: Are the header/footer bars for the dashboard and the About page generated in the same way? Because they actually seem different to me...see #71.

**Closed** 2016-05-25 20:25 UTC
Labels: layout, ready for review
